global:
  resolve_timeout: 5m
  smtp_from: 'alertmanager@example.org'
  smtp_smarthost: 'smtp.example.org:587'
  smtp_auth_username: 'alertmanager'
  smtp_auth_password: 'password'
  smtp_require_tls: true

route:
  group_by: ['alertname', 'job', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'team-email'
  routes:
  - match:
      severity: critical
    receiver: 'team-pager'
    continue: true
  - match_re:
      service: ^(api|transcription).*
    receiver: 'asr-team'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']

receivers:
- name: 'team-email'
  email_configs:
  - to: 'team@example.org'
    send_resolved: true

- name: 'team-pager'
  email_configs:
  - to: 'team-pager@example.org'
    send_resolved: true
  webhook_configs:
  - url: 'http://pagerduty-adapter:9096/'
    send_resolved: true

- name: 'asr-team'
  email_configs:
  - to: 'asr-team@example.org'
    send_resolved: true
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/TXXXXXXXX/BXXXXXXXX/XXXXXXXXXX'
    channel: '#asr-alerts'
    send_resolved: true
    title: '{{ template "slack.default.title" . }}'
    text: '{{ template "slack.default.text" . }}' 