global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "rules/alert_rules.yml"
  - "rules/recording_rules.yml"

# Scrape configurations
scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    metrics_path: '/metrics'
    static_configs:
    - targets: ['localhost:9090']
    
  # Scrape the API service
  - job_name: 'asr-api'
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
    - targets: ['api:8000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '(.*)'
        replacement: 'asr-api'
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'go_.*'
        action: drop

  # Scrape Node Exporter
  - job_name: 'node-exporter'
    static_configs:
    - targets: ['node-exporter:9100']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '(.*)'
        replacement: 'host'

  # Scrape cAdvisor
  - job_name: 'cadvisor'
    scrape_interval: 10s
    static_configs:
    - targets: ['cadvisor:8080']
    metric_relabel_configs:
      - source_labels: [container_name]
        regex: '/(prometheus|grafana|cadvisor|node-exporter|jaeger|api|ui).*'
        action: keep
        
  # Scrape Jaeger
  - job_name: 'jaeger'
    scrape_interval: 10s
    static_configs:
    - targets: ['jaeger:14269']
    
  # Scrape Grafana
  - job_name: 'grafana'
    scrape_interval: 10s
    static_configs:
    - targets: ['grafana:3000'] 